### ISSUE TITLE
package:angel_orm_mysql/angel_orm_mysql.dart missing?

### ISSUE THREAD

**Issue by u007** [angel-dart/orm#97]
hi,
how do i include this dependency?
is it published in pub.dev?

**Comment by u007** [comment]
nvm solved:
```
angel_orm_mysql:
    git:
      url: https://github.com/angel-dart/orm.git
      path: angel_orm_mysql
```
